print('Введите 1-ое число: ', end="")
num1 = int(input())
print('Введите 2-ое число: ', end="")
num2 = int(input())
print("Result: ", num1 + num2)
print("Result: ", num1 - num2)
print("Result: ", num1 / num2)
print("Result: ", num1 * num2)